### ISSUE TITLE
Hi! 关于类库的问题

### ISSUE THREAD

**Issue by xhzengAIB** [motianhuo/VCameraDemo#1]
@motianhuo 
你好！编译不能通过呢！请问是少提交了一些包吗？

Jack

**Comment by motianhuo** [comment]
您是指的Android studio版本么？请用最新版本编译

**Comment by zezhengwang** [comment]
com.yixia.camera.VCamera
com.yixia.camera.util
这两个jar找不到呢

**Comment by xhzengAIB** [comment]
com.yixia.camera.VCamera
com.yixia.camera.util

**Comment by zezhengwang** [comment]
大神 可以加个qq学习一下么

**Comment by motianhuo** [comment]
已经把引用库提交上了，请重新下载，谢谢支持！
